[package]
name = "mchprs_backend_direct"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
mchprs_backend_lib = { path = "../../backend_lib" }
serde_json = { workspace = true }
tracing = { workspace = true }
petgraph = { workspace = true }
itertools = { workspace = true }
rustc-hash = { workspace = true }
enum_delegate = { workspace = true }
indexmap = { workspace = true }
smallvec = { workspace = true }