FROM rust:slim

RUN apt-get update \
    && apt-get install -y \
    git pkg-config libssl-dev

RUN git clone https://github.com/MCHPR/MCHPRS.git
WORKDIR ./MCHPRS
RUN sed -i 's/pub const PLOT_SCALE: u32 = 4/pub const PLOT_SCALE: u32 = 5/g' crates/core/src/plot/mod.rs
RUN cargo install --path . \
    && cargo clean

VOLUME ["/data"]
WORKDIR /data

CMD ["mchprs"]